version: '3.9'
services:
  flutter-web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
    networks:
      - dm_network
networks:
  dm_network:
    external: true
