version: '3.9'
services:
  dm_api:
    build: .
    ports:
      - 8000:8000
    command: sh entrypoint.sh
    env_file:
      - .env
    networks:
      - dm_network
  mongodb:
    image: mongo
    restart: always
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_DATABASE}
    volumes:
      - dbmongo:/data/db
    networks:
      - dm_network

networks:
  dm_network:
    external: true

volumes:
  dbmongo: